#!/usr/bin/env python3
"""research.py — standalone research repository lifecycle.

`repo_root` (not a generated wiki) is the primary storage root for the pool architecture
(POOL_ARCHITECTURE_IMPLEMENTATION_PLAN.md). `wiki-manager` is not a runtime dependency for
any of this: `init` creates a self-contained repo, `project create` adds a manuscript
project inside it. Wiki import/export (`--from-wiki`, `export wiki`) is legacy
interoperability only — never required by the default path:

    research.py init -> project create -> ingest/search/extract -> appraise/synthesize/build

Subcommands
  init            <path> [--from-wiki <wiki-root>]     create/import a standalone repo
  project create  <slug> --repo <path>                 create a manuscript project
  project list    --repo <path>                        list projects in a repo

Environment: python3, stdlib only. No pip installs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import slugify, utcnow  # noqa: E402  (sibling module, stdlib-only)

SCHEMA_VERSION = 1

REPO_DIRS = (
    "data/sources/assets",
    "data/sources/snapshots",
    "data/papers/extractions",
    "data/papers/appraisals",
    "projects",
    "runs",
    "templates",
    "exports/wiki",
    "exports/bib",
    "exports/html",
    "exports/docx",
    "exports/pdf",
)
REPO_FILES = (
    "data/sources/events.jsonl",
    "data/papers/registry.jsonl",
    "data/papers/pool.jsonl",
)

PROJECT_DIRS = ("figures", "tables")
PROJECT_TEMPLATES = {
    "protocol.md": "# Protocol\n\n_Created {ts} by `research.py project create`._\n",
    "synthesis.md": "# Synthesis\n\n_Created {ts}._\n",
    "manuscript.qmd": "---\ntitle: \"{title}\"\n---\n\n_Created {ts}._\n",
    "refs.bib": "% refs.bib — generated by scripts/pool.py bib/render.py; do not hand-edit.\n",
}
PROJECT_TOUCH = ("corpus.lock.jsonl",)


def emit(obj: dict) -> None:
    print(json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=False))


def cmd_init(args) -> int:
    repo_root = Path(args.path).expanduser().resolve()
    created_dirs, created_files = [], []
    for rel in REPO_DIRS:
        d = repo_root / rel
        existed = d.exists()
        d.mkdir(parents=True, exist_ok=True)
        if not existed:
            created_dirs.append(rel)
    for rel in REPO_FILES:
        f = repo_root / rel
        if not f.exists():
            f.parent.mkdir(parents=True, exist_ok=True)
            f.touch()
            created_files.append(rel)

    imported = None
    if args.from_wiki:
        imported = _import_from_wiki(Path(args.from_wiki).expanduser().resolve(), repo_root)

    emit({
        "schema_version": SCHEMA_VERSION, "status": "ok", "command": "init",
        "repo_root": str(repo_root), "created_dirs": created_dirs,
        "created_files": created_files, "from_wiki": imported,
    })
    return 0


def _import_from_wiki(wiki_root: Path, repo_root: Path) -> dict:
    """Best-effort legacy bridge (plan "Backward Compatibility And Migration").

    Full migration (extraction/snapshot promotion, stale-pointer reporting) is the job of
    `pool.py migrate --from-wiki`; this only seeds the registry from an existing wiki pool
    so `research.py init --from-wiki` produces an immediately usable repo.
    """
    legacy_pool = wiki_root / "assets" / "papers" / "pool.jsonl"
    if not legacy_pool.exists():
        return {"wiki_root": str(wiki_root), "legacy_pool_found": False, "registered": 0}
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import registry as _registry
    reg = _registry.Registry(repo_root)
    count = 0
    with _registry.advisory_lock(repo_root, "registry"):
        with legacy_pool.open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                reg.register(rec)
                count += 1
        reg.save()
        reg.generate_pool()
    return {"wiki_root": str(wiki_root), "legacy_pool_found": True, "registered": count}


def cmd_project_create(args) -> int:
    repo_root = Path(args.repo).expanduser().resolve()
    slug = slugify(args.slug) if args.slug != slugify(args.slug) else args.slug
    project_dir = repo_root / "projects" / slug
    if project_dir.exists() and not args.force:
        emit({"schema_version": SCHEMA_VERSION, "status": "error", "command": "project create",
              "error": f"project already exists: {project_dir} (pass --force to reuse)"})
        return 1
    for rel in PROJECT_DIRS:
        (project_dir / rel).mkdir(parents=True, exist_ok=True)
    ts = utcnow()
    title = args.title or slug
    created = []
    for name, template in PROJECT_TEMPLATES.items():
        p = project_dir / name
        if not p.exists():
            p.write_text(template.format(ts=ts, title=title), encoding="utf-8")
            created.append(name)
    for name in PROJECT_TOUCH:
        p = project_dir / name
        if not p.exists():
            p.touch()
            created.append(name)
    emit({
        "schema_version": SCHEMA_VERSION, "status": "ok", "command": "project create",
        "repo_root": str(repo_root), "slug": slug, "project_dir": str(project_dir),
        "created": created,
    })
    return 0


def cmd_export_wiki(args) -> int:
    """Adapter, not part of the core pipeline (plan "Backward Compatibility And
    Migration": "Wiki export should be an adapter... manuscript creation, project
    storage... must work without it"). Two courtesy outputs for legacy wiki-manager
    consumers:

    1. `<wiki>/assets/papers/pool.jsonl` regenerated from the repo's canonical registry
       (reverse of `pool.py migrate`), so old wiki-mode `pool.py seed/lookup/bib` still see
       everything registered in the standalone repo.
    2. The project's `refs.bib`/`synthesis.md`/`manuscript.qmd` copied into
       `<wiki>/research/<project>/` as a bundle. This is a plain file copy, not
       `okf.py promote` (SKILL.md Stage 8) — it does not build an OKF-validated review page
       and is not a substitute for that publishing step.
    """
    repo_root = Path(args.repo).expanduser().resolve()
    wiki_root = Path(args.wiki).expanduser().resolve()
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import registry as _registry

    registry = _registry.Registry(repo_root)
    wiki_pool_path = wiki_root / "assets" / "papers" / "pool.jsonl"
    wiki_pool_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = wiki_pool_path.with_suffix(".jsonl.tmp")
    with tmp.open("w", encoding="utf-8") as fh:
        for eid in sorted(registry.records):
            fh.write(json.dumps(registry.records[eid], ensure_ascii=False, sort_keys=False))
            fh.write("\n")
    tmp.replace(wiki_pool_path)

    bundle_copied = []
    if args.project:
        project_dir = repo_root / "projects" / args.project
        dest_dir = wiki_root / "research" / args.project
        for name in ("refs.bib", "synthesis.md", "manuscript.qmd"):
            src = project_dir / name
            if src.exists():
                dest_dir.mkdir(parents=True, exist_ok=True)
                (dest_dir / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
                bundle_copied.append(name)

    emit({
        "schema_version": SCHEMA_VERSION, "status": "ok", "command": "export wiki",
        "repo_root": str(repo_root), "wiki_root": str(wiki_root),
        "pool_records_exported": len(registry.records), "pool_path": str(wiki_pool_path),
        "project": args.project, "bundle_copied": bundle_copied,
    })
    return 0


def cmd_project_list(args) -> int:
    repo_root = Path(args.repo).expanduser().resolve()
    projects_dir = repo_root / "projects"
    slugs = sorted(p.name for p in projects_dir.iterdir() if p.is_dir()) if projects_dir.exists() else []
    emit({"schema_version": SCHEMA_VERSION, "status": "ok", "command": "project list",
          "repo_root": str(repo_root), "projects": slugs})
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="research.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("init", help="create (or import) a standalone research repo")
    s.add_argument("path")
    s.add_argument("--from-wiki", dest="from_wiki",
                   help="legacy wiki root to seed the registry from (compatibility only)")
    s.set_defaults(func=cmd_init)

    proj = sub.add_parser("project", help="manuscript project lifecycle")
    proj_sub = proj.add_subparsers(dest="project_cmd", required=True)

    s = proj_sub.add_parser("create", help="create a manuscript project")
    s.add_argument("slug")
    s.add_argument("--repo", required=True)
    s.add_argument("--title", help="manuscript.qmd title (default: slug)")
    s.add_argument("--force", action="store_true", help="reuse an existing project directory")
    s.set_defaults(func=cmd_project_create)

    s = proj_sub.add_parser("list", help="list projects in a repo")
    s.add_argument("--repo", required=True)
    s.set_defaults(func=cmd_project_list)

    export = sub.add_parser("export", help="legacy wiki export adapter (never required)")
    export_sub = export.add_subparsers(dest="export_cmd", required=True)

    s = export_sub.add_parser("wiki", help="export pool.jsonl + a project bundle to a wiki")
    s.add_argument("--repo", required=True)
    s.add_argument("--wiki", required=True)
    s.add_argument("--project", help="also copy this project's refs.bib/synthesis.md/"
                                     "manuscript.qmd into <wiki>/research/<project>/")
    s.set_defaults(func=cmd_export_wiki)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
